blank_issues_enabled: true
contact_links:
  - name: Vulnérabilité de sécurité
    url: https://github.com/blue-broadcast/.github/blob/main/SECURITY.md
    about: NE PAS ouvrir d'issue publique. Suivre la politique de divulgation responsable.
